# Generated by Django 3.2.8 on 2021-11-03 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('last_access', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='My Portfolio', max_length=80, verbose_name='name')),
                ('is_main', models.BooleanField(default=False)),
                ('main_currency', models.CharField(default='KRW', max_length=10)),
                ('is_sub_currency', models.BooleanField(default=False)),
                ('sub_currency', models.CharField(default='USD', max_length=10)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
