# Generated by Django 3.2.8 on 2021-11-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='is_first',
            field=models.BooleanField(default=True),
        ),
    ]
