# Generated by Django 3.2.8 on 2021-10-30 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0006_auto_20211029_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='Currency',
            field=models.CharField(default='KRW', max_length=10),
        ),
    ]
