# Generated by Django 3.2.7 on 2021-10-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0007_portfolio_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountformat',
            name='code1',
            field=models.CharField(choices=[('0', 'default'), ('1', 'finance'), ('2', 'real estate')], default='0', max_length=2),
        ),
    ]
