# Generated by Django 3.2.7 on 2021-10-30 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0008_accountformat_code1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountformat',
            name='code1',
        ),
    ]
