# Generated by Django 3.2.7 on 2021-10-31 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_user', '0004_auto_20211031_0842'),
        ('portfolios', '0009_remove_accountformat_code1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountFormat',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='Currency',
            new_name='main_currency',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='is_sub_currency',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='sub_currency',
            field=models.CharField(default='USD', max_length=10),
        ),
    ]
