# Generated by Django 3.2.7 on 2021-10-31 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0010_auto_20211031_0842'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssetFormat',
        ),
    ]
