# Generated by Django 3.2.8 on 2021-11-02 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0011_delete_assetformat'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
