# Generated by Django 3.2.8 on 2021-11-03 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TickerSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.CharField(max_length=50, unique=True)),
                ('shortName', models.CharField(max_length=50, null=True)),
                ('longName', models.CharField(max_length=50, null=True)),
                ('currency', models.CharField(max_length=50, null=True)),
                ('financialCurrency', models.CharField(max_length=50, null=True)),
                ('country', models.CharField(max_length=50, null=True)),
                ('market', models.CharField(max_length=50, null=True)),
                ('exchange', models.CharField(max_length=50, null=True)),
                ('marketCap', models.CharField(max_length=50, null=True)),
                ('trailingPE', models.CharField(max_length=50, null=True)),
                ('dividendYield', models.CharField(max_length=50, null=True)),
                ('trailingEps', models.CharField(max_length=50, null=True)),
                ('beta', models.CharField(max_length=50, null=True)),
                ('currentPrice', models.CharField(max_length=50, null=True)),
                ('previousClose', models.CharField(max_length=50, null=True)),
                ('regularMarketPreviousClose', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
