# Generated by Django 3.2.8 on 2021-10-31 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickersymbol',
            name='dividendYield',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
