# Generated by Django 3.2.8 on 2021-11-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.CharField(max_length=50, null=True)),
                ('shortName', models.CharField(max_length=50, null=True)),
                ('currency', models.CharField(max_length=50, null=True)),
                ('regularMarketPrice', models.CharField(max_length=50, null=True)),
                ('previousClose', models.CharField(max_length=50, null=True)),
                ('regularMarketPreviousClose', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
