# Generated by Django 3.2.8 on 2021-10-31 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_market', '0002_alter_tickersymbol_dividendyield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickersymbol',
            name='beta',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tickersymbol',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tickersymbol',
            name='currency',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tickersymbol',
            name='currentPrice',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tickersymbol',
            name='exchange',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tickersymbol',
            name='financialCurrency',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tickersymbol',
            name='longName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tickersymbol',
            name='market',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tickersymbol',
            name='marketCap',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tickersymbol',
            name='shortName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tickersymbol',
            name='trailingEps',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tickersymbol',
            name='trailingPE',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
