# Generated by Django 3.2.8 on 2021-11-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_market', '0003_cyptousd'),
    ]

    operations = [
        migrations.AddField(
            model_name='cyptousd',
            name='currency',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cyptousd',
            name='fromCurrency',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cyptousd',
            name='marketCap',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cyptousd',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cyptousd',
            name='previousClose',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cyptousd',
            name='regularMarketPreviousClose',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cyptousd',
            name='regularMarketPrice',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cyptousd',
            name='shortName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cyptousd',
            name='symbol',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cyptousd',
            name='ticker',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cyptousd',
            name='toCurrency',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
