# Generated by Django 3.2.8 on 2021-11-05 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_market', '0004_auto_20211105_1051'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CyptoUSD',
            new_name='CryptoUSD',
        ),
    ]
