# Generated by Django 3.2.8 on 2021-11-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_market', '0005_rename_cyptousd_cryptousd'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerate',
            name='currency_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cryptousd',
            name='symbol',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cryptousd',
            name='ticker',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='currency',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='symbol',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
