# Generated by Django 3.2.8 on 2021-11-13 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_market', '0006_auto_20211105_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickersymbol',
            name='ticker',
        ),
    ]
