# Generated by Django 3.2.8 on 2021-11-13 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_market', '0007_remove_tickersymbol_ticker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptousd',
            name='ticker',
        ),
    ]
