# Generated by Django 3.2.8 on 2021-12-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_market', '0008_remove_cryptousd_ticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickersymbol',
            name='_yield',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tickersymbol',
            name='beta3Year',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tickersymbol',
            name='bookValue',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tickersymbol',
            name='dividendRate',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tickersymbol',
            name='enterpriseValue',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tickersymbol',
            name='exchangeTimezoneName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tickersymbol',
            name='exchangeTimezoneShortName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tickersymbol',
            name='forwardEps',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tickersymbol',
            name='lastDividendValue',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tickersymbol',
            name='legalType',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tickersymbol',
            name='priceToBook',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tickersymbol',
            name='quoteType',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tickersymbol',
            name='trailingAnnualDividendRate',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tickersymbol',
            name='trailingAnnualDividendYield',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
