# Generated by Django 3.2.8 on 2021-12-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_market', '0009_auto_20211204_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickersymbol',
            name='forwardPE',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tickersymbol',
            name='regularMarketPrice',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
