# Generated by Django 3.2.8 on 2021-12-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_market', '0010_auto_20211204_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickersymbol',
            name='exDividendDate',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tickersymbol',
            name='fiveYearAvgDividendYield',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
