# Generated by Django 3.2.8 on 2021-12-04 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_market', '0011_auto_20211204_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickersymbol',
            name='exDividendDate',
        ),
    ]
