# Generated by Django 3.2.8 on 2021-11-04 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetformat',
            name='code',
            field=models.CharField(default='', max_length=50),
        ),
    ]
