# Generated by Django 3.2.8 on 2021-11-05 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_support', '0002_assetformat_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetformat',
            name='amount_decimal_places',
        ),
    ]
