# Generated by Django 3.2.8 on 2021-11-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_support', '0003_remove_assetformat_amount_decimal_places'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetformat',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='financialaccountstitle',
            name='title',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
