# Generated by Django 3.2.8 on 2021-11-04 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolios', '0002_portfolio_is_first'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('last_access', models.DateTimeField(auto_now=True)),
                ('is_main', models.BooleanField(default=False)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='DataPortfolioStockthings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('last_access', models.DateTimeField(auto_now=True)),
                ('symbol', models.CharField(max_length=50)),
                ('amount', models.FloatField(default=0)),
                ('country', models.CharField(max_length=50)),
                ('dataportfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_portfolio.dataportfolio')),
            ],
        ),
    ]
