# Generated by Django 3.2.8 on 2021-11-04 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_portfolio', '0002_rename_dataportfoliostockthings_dataportfoliostockthing'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataportfoliostockthing',
            name='currency',
            field=models.CharField(default='', max_length=50),
        ),
    ]
