# Generated by Django 3.2.8 on 2021-11-03 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_support', '0001_initial'),
        ('data_user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FinancialAccountsTitle',
        ),
        migrations.AlterField(
            model_name='accountsasset',
            name='format',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data_support.assetformat'),
        ),
        migrations.DeleteModel(
            name='AssetFormat',
        ),
    ]
