# Generated by Django 3.2.8 on 2021-10-29 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0006_auto_20211029_1836'),
        ('data_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('attribute', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
            ],
        ),
        migrations.CreateModel(
            name='AssetsAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('action_time', models.DateTimeField()),
                ('amount_buy', models.DecimalField(decimal_places=2, max_digits=100)),
                ('amount_sell', models.DecimalField(decimal_places=2, max_digits=100)),
                ('rabel', models.CharField(max_length=100)),
                ('asset_buy', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='action_buy', to='data_user.accountsasset')),
                ('asset_sell', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='action_sell', to='data_user.accountsasset')),
            ],
        ),
        migrations.CreateModel(
            name='PortfoliosAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=50)),
                ('remark', models.TextField()),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='portfolios.accountformat')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='portfolios.portfolio')),
            ],
        ),
        migrations.DeleteModel(
            name='UsersAccounts',
        ),
        migrations.AddField(
            model_name='accountsasset',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='data_user.portfoliosaccount'),
        ),
        migrations.AddField(
            model_name='accountsasset',
            name='format',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='portfolios.assetformat'),
        ),
    ]
