# Generated by Django 3.2.8 on 2021-11-03 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_user', '0002_auto_20211103_0442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetsaction',
            name='account',
        ),
        migrations.AddField(
            model_name='assetsaction',
            name='account_buy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='action_account_buy', to='data_user.portfoliosaccount'),
        ),
        migrations.AddField(
            model_name='assetsaction',
            name='account_sell',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='action_account_sell', to='data_user.portfoliosaccount'),
        ),
        migrations.AlterField(
            model_name='assetsaction',
            name='asset_buy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='action_asset_buy', to='data_user.accountsasset'),
        ),
        migrations.AlterField(
            model_name='assetsaction',
            name='asset_sell',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='action_asset_sell', to='data_user.accountsasset'),
        ),
    ]
