# Generated by Django 3.2.7 on 2021-10-31 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_user', '0003_auto_20211030_0213'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAccountsTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('a', models.BooleanField(default=False, help_text='stocks, etf,,, exchange traded financial instruments')),
                ('b', models.BooleanField(default=False, help_text='crypto')),
                ('c', models.BooleanField(default=False, help_text='cash')),
                ('s', models.BooleanField(default=False, help_text='savings')),
                ('p', models.BooleanField(default=False, help_text='pension, retire, insurance, annuity,,,')),
            ],
        ),
        migrations.RemoveField(
            model_name='portfoliosaccount',
            name='code',
        ),
        migrations.RemoveField(
            model_name='portfoliosaccount',
            name='format',
        ),
        migrations.AddField(
            model_name='portfoliosaccount',
            name='a',
            field=models.BooleanField(default=False, help_text='stocks, etf,,, exchange traded financial instruments'),
        ),
        migrations.AddField(
            model_name='portfoliosaccount',
            name='b',
            field=models.BooleanField(default=False, help_text='crypto'),
        ),
        migrations.AddField(
            model_name='portfoliosaccount',
            name='c',
            field=models.BooleanField(default=False, help_text='cash'),
        ),
        migrations.AddField(
            model_name='portfoliosaccount',
            name='p',
            field=models.BooleanField(default=False, help_text='pension, retire, insurance, annuity,,,'),
        ),
        migrations.AddField(
            model_name='portfoliosaccount',
            name='r',
            field=models.BooleanField(default=False, help_text='real estate'),
        ),
        migrations.AddField(
            model_name='portfoliosaccount',
            name='s',
            field=models.BooleanField(default=False, help_text='savings'),
        ),
        migrations.AddField(
            model_name='portfoliosaccount',
            name='title',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='portfoliosaccount',
            name='z',
            field=models.BooleanField(default=False, help_text='painting, goods etc'),
        ),
        migrations.AlterField(
            model_name='assetsaction',
            name='rabel',
            field=models.CharField(choices=[('DF', 'default'), ('QK', '빠른생성'), ('TD', '거래'), ('IO', '입출'), ('IS', '내부거래'), ('US', '수정'), ('IR', '이자'), ('DD', '배당'), ('RT', '월세'), ('PY', '급여')], default='DF', max_length=2),
        ),
    ]
