# Generated by Django 3.2.8 on 2021-11-04 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_user', '0004_accountsasset_classi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountsasset',
            name='classi',
        ),
    ]
