# Generated by Django 3.2.7 on 2021-10-31 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_user', '0004_auto_20211031_0842'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
                ('amount_decimal_places', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='accountsasset',
            name='format',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='data_user.assetformat'),
        ),
    ]
