# Generated by Django 3.2.8 on 2021-10-31 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_user', '0006_tickersymbol'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TickerSymbol',
        ),
    ]
