# Generated by Django 3.2.8 on 2021-11-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_user', '0007_delete_tickersymbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsasset',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='assetsaction',
            name='action_time',
            field=models.DateTimeField(default=models.DateTimeField(auto_now_add=True)),
        ),
    ]
