# Generated by Django 3.2.8 on 2021-11-01 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_user', '0008_auto_20211101_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetsaction',
            name='asset_buy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='action_buy', to='data_user.accountsasset'),
        ),
        migrations.AlterField(
            model_name='assetsaction',
            name='asset_sell',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='action_sell', to='data_user.accountsasset'),
        ),
    ]
