# Generated by Django 3.2.8 on 2021-11-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_user', '0009_auto_20211101_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsasset',
            name='amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='assetformat',
            name='amount_decimal_places',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='assetsaction',
            name='amount_buy',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='assetsaction',
            name='amount_sell',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=100),
        ),
    ]
