# Generated by Django 3.2.8 on 2021-11-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_user', '0010_auto_20211101_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetsaction',
            name='action_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
